package christmas.Constant;

public class Constant {
    public static final String ERROR_VISIT_DATE_WRONG = "[ERROR] 유효하지 않은 날짜입니다. 다시 입력해 주세요.";
    public static final String ENTER_VISIT_DATE = "12월 중 식당 예상 방문 날짜는 언제인가요? (숫자만 입력해 주세요!)";
    public static final String ENTER_MENUS = "주문하실 메뉴를 메뉴와 개수를 알려 주세요. (e.g. 해산물파스타-2,레드와인-1,초코케이크-1)";
    public static final String ERROR_NOT_VALID_MENUS = "[ERROR] 유효하지 않은 주문입니다. 다시 입력해 주세요.";
    public static final Integer FIRST_INDEX = 0;
    public static final Integer SECOND_INDEX = 1;
    public static final String REG_EXPRESS = "^[가-힣]+-[0-9]+$" ;
    public static final Integer ZERO = 0;
    public static final Integer THIRTYTWO = 32;
    public static final Integer TWENTY = 20;
    public static final String HYPHEN = "-";
    public static final String COMMA = ",";
    public static final String BLANC_STRING = "";
    public static final String INTRO = "안녕하세요! 우테코 식당 12월 이벤트 플래너입니다.";
    public static final String ORDERED_MENU = "<주문 메뉴>";
    public static final String DECEMBER = "12월 ";
    public static final String EVENT_INTRO = "일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!";
    public static final String BLANC = " ";
    public static final String COUNT = "개";
    public static final String LUMP_SUM_BEFORE_DISCOUNT = "<할인 전 총주문 금액>";
    public static final String SUM_FORMAT = "%,d원\n";
    public static final String GIFT_MENU = "<증정 메뉴>";
    public static final String CHAMPAGNE = "샴페인 ";
    public static final String NOTHING = "없음";
    public static final String BENEFITS_LIST = "<혜택 내역>";
    public static final String CHRISTMAS_D_DAY_DISCOUNT_FORMAT = "크리스마스 디데이 할인: %,d원\n";
    public static final String WEEKDAY_DISCOUNT_FORMAT = "평일 할인: %,d원\n";
    public static final String WEEKEND_DISCOUNT_FORMAT = "주말 할인: %,d원\n";
    public static final String SPECIAL_DISCOUNT_FORMAT = "특별 할인: %,d원\n";
    public static final String GIFT_EVENT_PRICE = "증정 이벤트: -25,000원";
    public static final String BENEFITS_SUM_PRICE = "<총혜택 금액>";
    public static final String ESTIMATED_PAYMENT_AMOUNT_AFTER_DISCOUNT = "<할인 후 예상 결제 금액>";
    public static final String EVENT_BADGE = "<12월 이벤트 배지>";
    public static final Integer HUNDRED_TWENTY_THOUSAND = 120000;
    public static final Integer ONE = 1;
    public static final Integer TWELVE = 12;
    public static final Integer TWENTY_FIVE = 25;
    public static final Integer THIRTY_ONE = 31;
    public static final Integer TWO_THOUSAND_TWENTY_THREE = 2023;
    public static final Integer MINUS_THREE_THOUSAND_FOUR_HUNDRED = -3400;
    public static final Integer MINUS_ONE_THOUSAND = -1000;
    public static final Integer TEN_THOUSAND = 10000;
    public static final Integer MINUS_TWENTY_FIVE_THOUSAND = -25000;
    public static final Integer ONE_HUNDRED = 100;
    public static final Integer THREE = 3;
    public static final Integer TEN = 10;
    public static final Integer SEVENTEEN = 17;
    public static final Integer TWENTY_FOUR = 24;

}
